### PR TITLE
Resolving multiple compatibility issues with current credstash project

### PR DESCRIPTION
**Pull request by clintoncampbell**
This pull request covers three issues. The first two pertain to compatibility with the credstash project, while the 3rd change is to remove deprecated calls to the AWS SDK.

1. Calls to getItem or putItem with empty context resulted in a NullPointerException. I've added conditionals to guard against this and properly handle the case.
2. It seems there has been a change in HMAC encoding within the Dynamo object. While the current release expected to find HMAC as a String attribute. The credstash CLI is storing it as a binary attribute. I've accounted for both cases and now stash new items in the manner expected by the CLI, though testing is needed against older versions of the CLI.
3. The AWS client class constructors are now deprecated. I've modified constructors to leverage the builder classes as recommended in the latest documentation. Based on some testing, this may result in subtle changes in how the .aws/config and credential profiles are interpreted -- I've noticed that the Java SDK is quite finicky with these profiles. I also updated the dependency version in pom.xml and pulled in the latest BouncyCastle as well.

### CODE REVIEW

**Comment by BastianVoigt** [comment]
Hmm, no response?

**Comment by clintoncampbell** [comment]
None so far. Hoping we'll see something soon as I have some other pull requests around documentation and such once I complete some more urgent tasks.

**Comment by jessecoyle** [comment]
I'm closing this as I am recommending users to migrate away from Crestash (and this implementation)

**Comment by klamouri** [comment]
Hi @clintoncampbell 
In my organization we still rely on CredStash, as a result, I forked this project and put it in Maven Central, feel free to send this PR there https://github.com/klamouri/jcredstash

**Pull request closed without merging**
